pipeline {
    agent any
    
    environment {
        DOCKERHUB_CREDS = credentials('dockerhub-creds')
        AWS_ACCESS_KEY_ID = credentials('aws-access-key')
        AWS_SECRET_ACCESS_KEY = credentials('aws-secret-key')
        
        DOCKER_USERNAME = 'yuvalv1288' 
        IMAGE_NAME      = 'project-rolling-app'
        GIT_REPO_URL    = 'https://github.com/Yuvalvos/project-rolling.git'
    }
    
    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: "${GIT_REPO_URL}"
            }
        }
        
        stage('Parallel Checks') {
            parallel {
                stage('Linting - Flake8') {
                    steps {
                        // הרצה על תיקיית הפייתון החדשה
                        sh 'flake8 python/ || true' 
                    }
                }
                stage('Security - Trivy FS') {
                    steps {
                        sh 'trivy fs --severity HIGH,CRITICAL --no-progress .'
                    }
                }
            }
        }
        
        stage('Build Docker Image') {
            steps {
                sh "docker build -t ${DOCKER_USERNAME}/${IMAGE_NAME}:latest ."
            }
        }
        
        stage('Push to Docker Hub') {
            steps {
                sh "echo $DOCKERHUB_CREDS_PSW | docker login -u $DOCKER_USERNAME --password-stdin"
                sh "docker push ${DOCKER_USERNAME}/${IMAGE_NAME}:latest"
            }
        }
    }
}